#
# Cookbook Name:: php54
# Attribute:: default
#
## RPM Package
default['php54_php_package_name'] = "php54"
default['php54_php_version'] = "5.4.12-1.el5.maql"
default['php54_php-bcmath_version'] = node['php54_php_version']
default['php54_php-cli_version'] = node['php54_php_version']
default['php54_php-common_version'] = node['php54_php_version']
default['php54_php-dba_version'] = node['php54_php_version']
default['php54_php-devel_version'] = node['php54_php_version']
default['php54_php-embedded_version'] = node['php54_php_version']
default['php54_php-enchant_version'] = node['php54_php_version']
default['php54_php-gd_version'] = node['php54_php_version']
default['php54_php-intl_version'] = node['php54_php_version']
default['php54_php-ldap_version'] = node['php54_php_version']
default['php54_php-mbstring_version'] = node['php54_php_version']
default['php54_php-mcrypt_version'] = node['php54_php_version']
default['php54_php-mssql_version'] = node['php54_php_version']
default['php54_php-mysql_version'] = node['php54_php_version']
default['php54_php-mysqlnd_version'] = node['php54_php_version']
default['php54_php-odbc_version'] = node['php54_php_version']
default['php54_php-pdo_version'] = node['php54_php_version']
default['php54_php-pgsql_version'] = node['php54_php_version']
default['php54_php-process_version'] = node['php54_php_version']
default['php54_php-pspell_version'] = node['php54_php_version']
default['php54_php-recode_version'] = node['php54_php_version']
default['php54_php-snmp_version'] = node['php54_php_version']
default['php54_php-soap_version'] = node['php54_php_version']
default['php54_php-sqlite_version'] = node['php54_php_version']
default['php54_php-tidy_version'] = node['php54_php_version']
default['php54_php-xml_version'] = node['php54_php_version']
default['php54_php-xmlrpc_version'] = node['php54_php_version']
default['php54_php-debuginfo_version'] = node['php54_php_version']
default['php54_php-pear_version'] = "1.9.4-1.el5.maql"
default['php54_php-pecl-memcache_version'] = "2.2.7-1.el5.maql"
default['php54_php-pecl-yaml_version'] = "1.1.0-1.el5.maql"
default['php54_php-pecl-apc_version'] = "3.1.13-1.el5.maql"
default['php54_php-eaccelerator_version'] = "1.0-0.6.42067ac.el5.maql"
